@echo off
echo Cleaning up background terminals on port 8000...
FOR /F "tokens=5" %%a IN ('netstat -aon ^| findstr :8000') DO taskkill /PID %%a /F 2>nul
echo Done! Starting listener with OSINT Enrichment...
python main.py listen --enrich-osint
